// ===========================================
// ResearchAI — Export Utilities
// ===========================================

import { DocumentAnalysisResult } from "./ai-service";

export function downloadFile(content: string, fileName: string, contentType: string) {
  const blob = new Blob([content], { type: contentType });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = fileName;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}

export function exportAnalysisReportAsMarkdown(analysis: DocumentAnalysisResult, fileName: string = "Research_Report.md") {
  const md = `
# ResearchAI Analysis Report: ${fileName}

## Executive Summary
${analysis.executiveSummary}

## Short Summary
${analysis.shortSummary}

## Detailed Summary
${analysis.detailedSummary}

## Research Quality Score: ${analysis.qualityScore.overall}/100
- **Problem Definition:** ${analysis.qualityScore.breakdown.problemDefinition}/100
- **Methodology:** ${analysis.qualityScore.breakdown.methodology}/100
- **Data Analysis:** ${analysis.qualityScore.breakdown.dataAnalysis}/100
- **Results:** ${analysis.qualityScore.breakdown.results}/100
- **Writing Quality:** ${analysis.qualityScore.breakdown.writingQuality}/100

### Strengths
${analysis.qualityScore.strengths.map(s => `- ${s}`).join("\n")}

### Weaknesses & Recommendations
${analysis.qualityScore.recommendations.map(r => `- ${r}`).join("\n")}

## Key Findings
${analysis.keyFindings.map(k => `- ${k}`).join("\n")}

## Methodology
${analysis.methodology}

## Results & Discussion
${analysis.results}

## Conclusion
${analysis.conclusion}

## Keywords
${analysis.keywords.join(", ")}

---
*Generated by ResearchAI — Turn Research Into Impact.*
  `.trim();

  downloadFile(md, fileName.replace(/\.[^/.]+$/, "") + "_Analysis_Report.md", "text/markdown;charset=utf-8;");
}

export function exportCitationsAsBibTeX(citations: DocumentAnalysisResult["citations"], fileName: string = "citations.bib") {
  const bib = citations
    .map((c, i) => `@article{source${i + 1},\n  author = {${c.suggestedSource}},\n  title = {${c.claim}},\n  note = {${c.citation}}\n}`)
    .join("\n\n");
  downloadFile(bib, fileName, "text/plain;charset=utf-8;");
}

export function exportSlidesAsJSON(slides: DocumentAnalysisResult["presentationSlides"], fileName: string = "presentation.json") {
  const jsonStr = JSON.stringify(slides, null, 2);
  downloadFile(jsonStr, fileName, "application/json");
}
