import { NextRequest, NextResponse } from "next/server";
import { prisma } from "@/lib/db";
import { cookies } from "next/headers";
import { readFile } from "fs/promises";
import path from "path";

export async function GET(
  req: NextRequest,
  { params }: { params: Promise<{ id: string }> }
) {
  try {
    const { id } = await params;
    const cookieStore = await cookies();
    const sessionToken = cookieStore.get("session-token")?.value;

    if (!sessionToken) {
      return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
    }

    const session = await prisma.session.findUnique({
      where: { sessionToken },
      select: { userId: true },
    });

    if (!session) {
      return NextResponse.json({ error: "Session invalid" }, { status: 401 });
    }

    const document = await prisma.document.findUnique({
      where: { id },
      include: { analysis: true },
    });

    if (!document || document.userId !== session.userId) {
      return NextResponse.json({ error: "Document not found" }, { status: 404 });
    }

    // Try reading physical file if exists
    try {
      const filePath = path.join(process.cwd(), "uploads", document.storageKey);
      const fileBuffer = await readFile(filePath);

      return new NextResponse(fileBuffer, {
        headers: {
          "Content-Type": document.fileType || "application/octet-stream",
          "Content-Disposition": `attachment; filename="${document.fileName}"`,
        },
      });
    } catch {
      // Fallback: Generate structured Markdown export if file is sample/demo
      const analysis = document.analysis;
      let keyFindingsText = "";
      if (analysis?.keyFindings) {
        try {
          const parsed = typeof analysis.keyFindings === "string" ? JSON.parse(analysis.keyFindings) : analysis.keyFindings;
          if (Array.isArray(parsed)) {
            keyFindingsText = parsed.map((k: any) => `- ${k}`).join("\n");
          }
        } catch {}
      }

      const reportMarkdown = `# ResearchAI Report: ${document.fileName}
      
## Executive Summary
${analysis?.executiveSummary || "No executive summary available."}

## Short Summary
${analysis?.shortSummary || "No short summary available."}

## Detailed Summary
${analysis?.detailedSummary || "No detailed summary available."}

## Key Findings
${keyFindingsText}

---
*Generated by ResearchAI Platform*`;

      return new NextResponse(reportMarkdown, {
        headers: {
          "Content-Type": "text/markdown; charset=utf-8",
          "Content-Disposition": `attachment; filename="${document.fileName.replace(/\.[^/.]+$/, "")}_Report.md"`,
        },
      });
    }
  } catch (error) {
    console.error("Document download error:", error);
    return NextResponse.json({ error: "Failed to download material" }, { status: 500 });
  }
}
